name: battenberg
channels:
  - conda-forge
  - bioconda
dependencies:
  - procps-ng
  - r-base=4.3
  - r-remotes
  - r-devtools
  - r-biocmanager
  - r-data.table
  - r-dplyr
  - r-ggplot2
  - r-optparse
  - r-gtools
  - r-foreach
  - r-doparallel
  - bioconductor-genomicranges
  - bioconductor-variantannotation
  - cancerit-allelecount
  - samtools
  - impute2
  - htslib
  - openjdk=8
  - wget
  - curl
  - git
  - unzip
