name: Build Docker image

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/battenberg-beagle:latest \
            -t ghcr.io/${{ github.repository_owner }}/battenberg-beagle:v0.2 \
            .

      - name: Test Docker image
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/battenberg-beagle:latest Rscript /usr/local/bin/test_install.R

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/battenberg-beagle:latest
          docker push ghcr.io/${{ github.repository_owner }}/battenberg-beagle:v0.2
